// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.startupRolloutPrefs.media.autoplay.default", 1);
user_pref("app.normandy.user_id", "7c235581-7caf-4082-b930-f0ed1914fc6f");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1555332487);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1555571567);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1555571447);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1555571932);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 757760);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1555332455);
user_pref("browser.laterrun.bookkeeping.sessionCount", 6);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.impressionId", "{82a9d8c2-3434-4c73-84ff-c7f2948eb3ad}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1555520400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1555571462170");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1555573243170");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1555571435300");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1555575035300");
user_pref("browser.search.region", "ID");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190327091201");
user_pref("browser.slowStartup.averageTime", 3056);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190327091201");
user_pref("browser.startup.homepage_override.mstone", "66.0.2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 1);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1555332493762");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "66.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "01f43a898cf845f2a5391a39726209bc");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190327091201");
user_pref("extensions.lastAppVersion", "66.0.2");
user_pref("extensions.lastPlatformVersion", "66.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"96c4eb58-fc6a-4e56-a711-8a41ff2606c7\",\"screenshots@mozilla.org\":\"4e4c8080-597b-4889-84d7-3e345f059b88\",\"webcompat-reporter@mozilla.org\":\"c72fcea7-27a9-4a91-9ce6-8d078d7337ed\",\"webcompat@mozilla.org\":\"df940e4b-cda9-41ff-87d4-1618b6e8015e\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "df962ceb-c9e9-4836-a8a7-23af385ad695");
user_pref("security.sandbox.plugin.tempDirSuffix", "835caa59-6a68-4b75-b758-ac63587f822b");
user_pref("services.settings.clock_skew_seconds", -39);
user_pref("services.settings.last_update_seconds", 1555571972);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1555572407);
user_pref("toolkit.telemetry.cachedClientID", "e7fe7d25-8756-4736-bf5a-590a2f07623c");
user_pref("toolkit.telemetry.previousBuildID", "20190327091201");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
